developer-mode: false
anomaly-check-rate: 100
anomaly-particles-check-rate: 10
chat:
  local:
    radius: 25.0
    discord-channel-id: 0
  global:
    discord-channel-id: 0
resource-pack:
  version:
  user: minersstudios
  repo: mstextures
  full:
    file-name: full-msTextures-%s.zip
    hash:
  lite:
    file-name: lite-msTextures-%s.zip
    hash:
